jd_scripts:
  image: lxk0301/jd_scripts
  # 配置服务器资源约束。此例子中服务被限制为使用内存不超过200M以及cpu不超过0.2（单核的20%）
  # 经过实际测试，建议不低于200M
  # deploy:
  #   resources:
  #     limits:
  #       cpus: '0.2'
  #       memory: 200M
  container_name: jd_scripts
  restart: always
  volumes:
    - ./logs:/scripts/logs
    - ./start.sh:/scripts/start.sh
    - ./my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
  tty: true
  # 因为更换仓库地址可能git pull的dns解析不到，可以在配置追加hosts
  # extra_hosts:
  #   - "gitee.com:180.97.125.228"
  #   - "github.com:13.229.188.59"
  #   - "raw.githubusercontent.com:151.101.228.133"
  environment:
    # #UserAgent
    # - JD_USER_AGENT=JD4iPhone/9.4.1 CFNetwork/1236 Darwin/20.4.0
    # 互相助力
    - SHARE_CODE_FILE=/scripts/logs/sharecode.log
    #脚本更新仓库地址，配置了会切换到对应的地址
    - REPO_URL=git@gitee.com:lxk0301/jd_scripts.git
    # 注意环境变量填写值的时候一律不需要引号（""或者''）下面这些只是事例，根据自己的需求增加删除
    #jd cookies
    - JD_COOKIE=pt_key=AAJgHr4AADBqjMYpzpJn9fbWJV72339YjlrHAU3tK-gnO0WgY8DUUghurIlLV6mC_uuNu-5umPA;pt_pin=61235351-77393574;&pt_key=AAJgHsQRADAHoiRcnSKH5F-elfi27QhgE9YCKEGQLtDOsPjkQcenxsSeGuOWjmvdA7vC-5s7NDw;pt_pin=jd_nhGEMTsLFjxH;&pt_key=AAJgPbtbADDP-e7rZTMncwlsubotxZ9gbhSrK5YRqeabNyXdMgo0hB-4t_jhOZ74dwS-9ZjrqBI;pt_pin=jd_eDAjMQZivmUq;&pt_key=AAJgPblAADC6tTyAk3BGIPPhdZk81hHQtHY7RCX6XilSpQ67hr4OE95PTwFuW7SLBLt4DuFnoNY;pt_pin=jd_657d354558d04;&pt_key=AAJgNIzxADC49iAPcvQre9H_g-FKGCKxh6tzxMKtRpm8JUOeodY_GJ7Gi9kBhzzO4-MTFvV_Iu8;pt_pin=jd_61bf3e45607ba;&pt_key=AAJgPbuvADD5qqN8UeRZ_WMPwVY9xzI6-GmfRqZY6BdTaFib_i1z5EA1oLg3gKMP9M5iEjgOFbM;pt_pin=%E8%BE%BE%E7%93%A6%E9%87%8C%E6%96%BD%E5%96%86;&pt_key=AAJgMPZoADAnh1oMhB8NAjsZjRAwBooNvrqakqmb8uDTtbYdIMKFbynKAMBrBSLOlyHWaNfVvFE;pt_pin=jd_77ca3b5be6541;&pt_key=AAJgMKIXADAJqfIMwc4rvNItjMCARuXILkI66N8Ty2wiTp3NpCAxsx68jkk7xSig0n06ZShY3nY;pt_pin=jd_UEJyFmhOjKdO;&pt_key=AAJgH926ADC9dotlSyfo3E7RIdlGOr6GpffDslBCDsZrFb-wB6gtKvHG1oorXqSImFSXB611SAI;pt_pin=jd_551736b984eaf;&pt_key=AAJgJL-kADAyui2w2-rh46zPwW2LLcgGAwGJmjnbIozwfiKiO2OPBCCVEGvOe1IbJMoCbM_Y2FA;pt_pin=jd_46e1426b4871e;&pt_key=AAJgMPw-ADAUgf5gwa8phi6aoxgOy1OwzE1rPYURLXObw2FmPX8e2Vu1YLR3xJ6MR8uJTDKMIMs;pt_pin=jd_NhjyKogNXbwk;&pt_key=AAJgJo6MADAdD0Fra0PdIizVPEE6xZvq4vFfmClRn_cYtLkqZ_3ZPf4EtidryllWBdESAbAxUsE;pt_pin=jd_6efb604d64013;&pt_key=AAJgH9vNADCA10IxkW2zdksSUGZPPKy8NxOgy7FuBQXwc625O72Rq4tAg3ddwO_QVLrazBibRY0;pt_pin=jd_7a151517ac2e6;


    - QYWX_KEY=1ff2a6f8-704b-403c-8cae-23d1c0287021
    - DD_BOT_TOKEN=5a112634548ad35387da3de21ef1b4218954fe067a89cd1d3c03ec0c162ebf3e
    - DD_BOT_SECRET=SEC47af9fc335072bcc5003b124ad1e84055edf7db015fdee4005b3b27f8041f655

    # 种豆得豆
    - PLANT_BEAN_SHARECODES=
    # 京东农场
    - FRUITSHARECODES=
    # 京东萌宠
    - PETSHARECODES=
    # 京喜工厂
    - DREAM_FACTORY_SHARE_CODES=
    # 东东工厂
    - DDFACTORY_SHARECODES=
    # crazyJoy
    - JDJOY_SHARECODES=
    # 京喜农场
    - JXNC_SHARECODES=
    # 闪购盲盒
    - JDSGMH_SHARECODES=
    # 财富岛
    - JDCFD_SHARECODES=


    # 农场使用水滴换豆卡
    - FRUIT_BEAN_CARD=true
    # 多合一签到延迟
    - JD_BEAN_STOP=1500
    # 购买joy等级
    - BUY_JOY_LEVEL=30
    # 兑换多少数量的京豆（20，或者1000京豆,或者其他奖品的文字）
    - MARKET_COIN_TO_BEANS=1000
    # 宠汪汪的喂食数量
    - JOY_FEED_COUNT=10
    - JD_JOY_REWARD_NAME=500
    # 东东超市使用金币去抽奖,true表示抽奖
    - SUPERMARKET_LOTTERY=true
    # 东东超市兑换奖品推送静默,false为发送推送通知消息
    - MARKET_REWARD_NOTIFY=false
    #是否开启debug模式打印日志
    - JD_DEBUG=true
    # 京喜工厂不运行脚本
    - DREAMFACTORY_FORBID_ACCOUNT=2
    #如果设置了 RANDOM_DELAY_MAX ，则会启用随机延迟功能，延迟随机 0 到 RANDOM_DELAY_MAX-1 秒。如果不设置此项，则不使用延迟。
    #并不是所有的脚本都会被启用延迟，因为有一些脚本需要整点触发。延迟的目的有两个，1是降低抢占cpu资源几率，2是降低检查风险（主要是1）
    #填写数字，单位为秒，比如写为 RANDOM_DELAY_MAX=30  就是随机产生0到29之间的一个秒数，执行延迟的意思。
    - RANDOM_DELAY_MAX=300
